FROM node:lts-alpine


WORKDIR /app
# COPY package.json ./
# COPY package-lock.json ./
# COPY ./ ./
# RUN npm i
# RUN chmod +x ./core/bin/run.sh


# Uses port which is used by the actual application
EXPOSE 3000

CMD ["npm", "start"]

