name: Cut Tag and Release

on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

run-name: Tag and release

permissions:
  contents: write
  packages: write

jobs:
  build-and-push-image:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Get tag version
      id: TAG
      run: |
        release_version=$(npm version patch --no-git-tag-version --no-push | sed 's/v//g')
        echo "Version is ${release_version}"
        echo "release_version=$release_version" >> $GITHUB_OUTPUT

    - name: Push changes
      run: |
        git fetch
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add --all
        git commit -am "Relase version ${{ steps.TAG.outputs.release_version }}"
        git push

    - name: Tag release
      run: |
        git tag -a ${{ steps.TAG.outputs.release_version }} -m "tag release ${{ steps.TAG.outputs.release_version }}"
        git push --follow-tags

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ steps.TAG.outputs.release_version }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}